#!/usr/bin/env bash

PROFILE=$1

set -e
#set -x

function run_test() {

  export main_src="$1"

  export flags="$2"

  export exclude="$3"

  export headers=$(find -L src -name "*.h" | xargs -I% dirname % | uniq | grep -v libs | grep -v test | grep -v unity | grep -v "$exclude" | xargs -I% echo "-I %")
  export src_c=$(find -L src -name "*.c" | grep -v test | grep -v unity | grep -v libs |  grep -v "$exclude"  | xargs -I% echo " %")
  export src_cpp=$(find -L src -name "*.cpp" | grep -v test | grep -v unity | grep -v libs | grep -v "$exclude" | xargs -I% echo " %")

  export headers_unity="-I libs/Unity/src"
  export src_unity="libs/Unity/src/*.c"

  rm -f ./simulator.bin

  cmd_l="g++ -Wno-deprecated-declarations -g -ggdb -o simulator.bin $flags "$PLATFORMIO_BUILD_FLAGS" $src_c $src_cpp $src_unity $main_src $headers -I src $headers_unity"
  $cmd_l 

  ./simulator.bin
  #cgdb simulator.bin

  rm ./simulator.bin

}


source mavarduino.conf
export PLATFORMIO_BUILD_FLAGS="-D PROJ_VERSION=`git rev-parse --short HEAD` `cat $PROFILE`"



for f in $(find test -name *.cpp)
do
  echo ""
  echo ""
  echo "### Running $f"
  echo ""
  echo ""
  run_test "$f" "$test_general_flags" "$test_excludes_pattern"
done

