#!/usr/bin/env bash

set -e
#set -x

function run_test() {

  export main_src="$1"

  export flags="$2"

  export exclude='Adafruit\|EspSaveCrash\|catch'

  export headers=$(find * -name "*.h" | xargs -I% dirname % | uniq | grep -v test | grep -v unity | grep -v "$exclude" | xargs -I% echo "-I %")
  export src_c=$(find * -name "*.c" | grep -v test | grep -v unity | grep -v "$exclude"  | xargs -I% echo " %")
  export src_cpp=$(find * -name "*.cpp" | grep -v test | grep -v unity | grep -v "$exclude" | xargs -I% echo " %")

  export headers_unity="-I lib_deps_external/Unity/src"
  export src_unity="lib_deps_external/Unity/src/*.c"

  g++ -Wno-deprecated-declarations -o simulator.bin $flags $src_c $src_cpp $src_unity $main_src $headers -I src $headers_unity

  ./simulator.bin

  rm ./simulator.bin

}

rm -fr lib_deps_external/Unity/examples


general_flags="-D UNIT_TEST -D LOG_LEVEL=0 -D OVERRUN_THRESHOLD_SECS=10000"

for f in $(find test -name *.cpp)
do
  echo ""
  echo ""
  echo "### Running $f"
  echo ""
  echo ""
  run_test "$f" "$general_flags"
done
