#!/usr/bin/env bash

# Encrypt and publish sensitive setup information
# for your devide. This includes wifi ssid and password. 
# Usage: 
#   script <device> <wifi_ssid> <wifi_password> <encryption_key>

PRETTY='python -m json.tool'

DEVICE=$1
WIFI_SSID=$2
WIFI_PASSWORD=$3
KEY_HEX=${4:-11112233445566778899aabbccddeeff}

# Print a single-line hexadecimal representation of a file's content.
function file_to_hex() {
  local f=$1
  xxd -ps "$f" | tr '\n' ' ' | sed 's/ //g'
}


# Encrypt an input string given a key
function ecb_encrypt() {
  local input="$1"
  local key="$2"
  local inputf=`mktemp`
  local outputf=`mktemp`
  echo "$input" > "$inputf"
  local size=${#input}
  local remaining=`echo "31 - $size" | bc`

  xxd -ps "$inputf" > /tmp/k-input-$input

  dd if=/dev/zero of="$inputf" bs=1 seek="$size" count="$remaining" # fill in remaining bytes with null chars

  echo $size > /tmp/k-size-$input
  echo $remaining > /tmp/k-remaining-$input
  xxd -ps $inputf > /tmp/k-inputpadded-$input

  openssl enc -aes-128-ecb -nosalt -K "$key" -in "$inputf" -out "$outputf"
  echo $outputf
}

WIFI_SSID_ENCRYPTED=$(file_to_hex `ecb_encrypt "$WIFI_SSID" "$KEY_HEX"`)
WIFI_PASSWORD_ENCRYPTED=$(file_to_hex `ecb_encrypt "$WIFI_PASSWORD" "$KEY_HEX"`)

# Set up settings
url="http://dweet.io/dweet/for/$DEVICE-setup?"
url+="ssid=$WIFI_SSID_ENCRYPTED&"
url+="pass=$WIFI_PASSWORD_ENCRYPTED"
curl -XPOST $url | $PRETTY

echo "# Done."
