#!/usr/bin/env bash

PRETTY='python -m json.tool'

DEVICE=$1
WIFI_SSID=$2
WIFI_PASSWORD=$3
KEY=${4:-11112233445566778899aabbccddeeff}
ENCRYPTED_PASS=$5

echo "# Creating input file (content $WIFI_PASSWORD)..."
echo "$WIFI_PASSWORD" > body.bin

echo "# Input file..."
cat body.bin

echo "# Encrypting file (key $KEY)..."
echo $KEY | xxd -r -p > pass
openssl enc -aes-128-ecb -nosalt -K $KEY -in body.bin -out body.ecb.bin  

echo "# Showing output file..."
WIFI_PASSWORD_ENCRYPTED=`xxd -ps body.ecb.bin`

# Set up settings
url="http://dweet.io/dweet/for/$DEVICE-setup?"
url+="ssid=$WIFI_SSID&"
if [ "$ENCRYPTED_PASS" == "" ]
then
  url+="pass=$WIFI_PASSWORD_ENCRYPTED"
else
  url+="pass=$ENCRYPTED_PASS"
fi
curl -XPOST $url | $PRETTY

echo "# Done."
