#!/usr/bin/env bash

DEVICE=${1:-dev1}

PRETTY='python -m json.tool'

# Set up general settings
url="http://dweet.io/dweet/for/$DEVICE-settings-target?"
url+='lcddebug=false&' # turn on/off LCD DEBUG (show logs in LCD)
url+='crashclear=false&' # do not clear debug info (stacktraces) from device
url+='loglevel=1' # log level
curl -XPOST $url | $PRETTY

# Set up body
url="http://dweet.io/dweet/for/$DEVICE-body-target?"
url+="im1=00001EF0021000000000000007E00000&" # image doubtful
url+="im2=00000280129010100FE0014001400080&" # image mischeavious
url+="msg0=KEEP%20CALM%0AAND%20GIT%20PUSH&" # message
url+="msg1=A%20BUG%0ALIVES%0AIN%20ME&" # message
url+="msg2=KEEP%20IT%0ACLEAN&" # message
url+="msg3=DRINK%A0WATER&" # message
url+="mv0=Fs.W4.M02W5.Mc4Zzi&" # move
url+="mv1=F1.W4.M12W5.Mc4Zz.&" # move
url+="mv2=F2.W4.M22W5.Mc4Zz.&" # move
url+="mv3=Fw.Fb.M32W5.Zz.&" # move
url+="t0=0&" # timing
url+="t1=0&" # timing
url+="t2=0&" # timing
url+="t3=201016060&" # timing
curl -XPOST $url | $PRETTY

# Set up properties synchronizer
url="http://dweet.io/dweet/for/$DEVICE-propsync-target?"
url+="freq=201010560" # sync all properties every 5 minutes
curl -XPOST $url | $PRETTY

# Set up setup synchronizer (for wifi setup)
url="http://dweet.io/dweet/for/$DEVICE-setupsync-target?"
#url+="freq=201010560" # sync all properties every 5 minutes
curl -XPOST $url | $PRETTY

