#!/usr/bin/env bash

DEVICE=${1:-dev1}

PRETTY='python -m json.tool'

function curl_cmd(){
  echo "-> $1"
  curl --silent -XPOST $1 | $PRETTY
}

# Set up general settings
url="http://dweet.io/dweet/for/$DEVICE-settings-target?"
url+='lcddebug=false&' # turn on/off LCD DEBUG (show logs in LCD)
url+='crashclear=false&' # do not clear debug info (stacktraces) from device
url+='loglevel=0' # log level
curl_cmd $url

# Set up messages (to be used by the body)
url="http://dweet.io/dweet/for/$DEVICE-messages-target?"

url+="msg0=H2O&" # custom message
url+="msg1=STANDUP&" # custom message
curl_cmd $url

# Set up images (to be used by the body)
url="http://dweet.io/dweet/for/$DEVICE-images-target?"
url+="im0=00002814100828140000000003C00000&"
curl_cmd $url


# Set up body
url="http://dweet.io/dweet/for/$DEVICE-body-target?"

url+="mv0=LwyMp1BB88W9.W9.Zz.&" # move fun
url+="t0=0" # timing fun

url+="mv1=Mc4W9.Zz.&" # move clock
url+="t1=201016060&" # timing clock

url+="mv2=B99M13W9.F0.W9.M13W9.Zz.&" # move standup
url+="t2=177103000&" # timing standup

url+="mv3=LwyM04W9.Zz.&" # move H20
url+="t3=201016060&" # timing H20

curl_cmd $url

# Set up properties synchronizer
url="http://dweet.io/dweet/for/$DEVICE-propsync-target?"
url+="freq=201011560" # sync all properties every 15 minutes
url+="updateprops=true"
url+="updateinfos=true"
curl_cmd $url

# Set up setup synchronizer (for wifi setup)
#url="http://dweet.io/dweet/for/$DEVICE-setupsync-target?"
#url+="freq=201012060" # sync every 20 minutes
#curl_cmd $url

