#!/usr/bin/env bash

DEVICE=${1:-dev1}

PRETTY='python -m json.tool'

function curl_cmd(){
  echo "-> $1"
  curl --silent -XPOST $1 | $PRETTY
}

# Set up general settings
url="http://dweet.io/dweet/for/$DEVICE-settings-target"
url+="?"
url+='lcddebug=false' # turn on/off LCD DEBUG (show logs in LCD)
url+="&"
url+='crashclear=false' # do not clear debug info (stacktraces) from device
url+="&"
url+='loglevel=0' # log level
curl_cmd $url

# Set up messages (to be used by the body)
url="http://dweet.io/dweet/for/$DEVICE-messages-target"
url+="?"
url+="msg0=H2O" # custom message
url+="&"
url+="msg1=STANDUP" # custom message
curl_cmd $url

# Set up images (to be used by the body)
url="http://dweet.io/dweet/for/$DEVICE-images-target"
url+="?"
url+="im0=00002814100828140000000003C00000"
curl_cmd $url


# Set up body
url="http://dweet.io/dweet/for/$DEVICE-body-target"
url+="?"
url+="mv0=LryA99A09Fs2W5.Zz." # move fun
url+="&"
url+="t0=0" # timing fun
url+="&"
url+="mv1=Mc4W9." # move clock
url+="&"
url+="t1=201016060" # timing clock
url+="&"
url+="mv2=B99M13W9.F0.W9.M13W9.W9.Zz." # move standup
url+="&"
url+="t2=177101500" # timing standup
url+="&"
url+="mv3=LwyM04W9.Zz." # move H20
url+="&"
url+="t3=201016060" # timing H20

curl_cmd $url

# Set up properties synchronizer
url="http://dweet.io/dweet/for/$DEVICE-propsync-target?"
url+="freq=201011560" # sync all properties every 15 minutes
url+="&"
url+="updateprops=true"
url+="&"
url+="updateinfos=true"
curl_cmd $url

# Set up clock synchronizer
url="http://dweet.io/dweet/for/$DEVICE-clocksync-target?"
url+="freq=201066060" # sync clock once every 6 hours
curl_cmd $url

