#!/usr/bin/env bash

set -x 
set -e

rm -f .simulator.bin

PROFILE="$1"

PARAM_FLAGS="-D PROJ_VERSION=simulation `cat $PROFILE`"

FLAGS="-D SIMULATE $PARAM_FLAGS"

SRC="
src/Main.cpp
src/Time.cpp
src/DateStrings.cpp
src/main4ino/*.cpp
src/log4ino/*.cpp
"

HEADERS="
-I src/
-I src/actors/
-I src/log4ino
-I src/main4ino
"

LIBS=""

g++ -Wno-deprecated-declarations -g -ggdb -o .simulator.bin $FLAGS $SRC $HEADERS $LIBS
shift
./.simulator.bin $@
#gdbtui ./.simulator.bin
rm -f .simulator.bin
