#!/usr/bin/env bash

set -x 
set -e

rm -f .simulator.bin

PARAM_FLAGS="$@"

FLAGS="
-D WIFI_SSID_INIT=\"wifi\"
-D WIFI_PASSWORD_INIT=\"pass\"
-D ENCRYPT_KEY=\"11112233445566778899aabbccddeeff\"
-D TIMEZONE_DB_KEY=\"akey\"
-D TIMEZONE_DB_ZONE=\"Europe/Paris\"
-D UNIT_TEST
-D LOG_LEVEL=0
-D DEVICE_NAME=\"simulated\"
-D MAX_LOG_MSG_LENGTH=1024
-D PERIOD_SEC=1
-D SIMULATE
$PARAM_FLAGS
"

SRC="
src/Main.cpp
src/aes.c
src/Time.cpp
src/DateStrings.cpp
src/main4ino/*.cpp
src/log4ino/*.cpp
"

HEADERS="
-I src/
-I src/actors/
-I src/log4ino
-I src/main4ino
"

LIBS=""

g++ -Wno-deprecated-declarations -g -ggdb -o .simulator.bin $FLAGS $SRC $HEADERS $LIBS
#./.simulator.bin
gdbtui ./.simulator.bin
rm -f .simulator.bin
