#!/usr/bin/env bash

set -e
set -x

while getopts p:fmsv option
do
  case "${option}"
  in
    p) PROFILE=${OPTARG};;
    f) UPLOAD_FIRMWARE=true;;
    m) MONITOR=true;;
    s) UPLOAD_FS=true;;
    v) PLATFORMIO_RUN_PARAMS="-v";;
  esac
done

if [ -z "$PROFILE" ]
then
  echo "Variable -p PROFILE is mandatory"
  exit 1
fi

VERSION=`cat library.json | python -c 'import sys, json; print json.load(sys.stdin)["version"]'`
COMMIT_ID="`git rev-parse --short HEAD`"
PROJ_VERSION_ID="$VERSION-$COMMIT_ID" 
LOG_DIR=images

echo "### Using profile $PROFILE..."
export PLATFORMIO_BUILD_FLAGS="-D PROJ_VERSION=$PROJ_VERSION_ID `cat $PROFILE | grep -v '^#'`" 

echo "### Compiling..."
platformio run $PLATFORMIO_RUN_PARAMS

if [ -n "$UPLOAD_FIRMWARE" ]
then

  echo "### Will upload firmware..."

  echo "### Checking if no changes to be committed..."
  git diff --exit-code

  echo "### Uploading..."
  platformio run --target upload

  echo "### Backing up image..."
  mkdir -p $LOG_DIR/$PROJ_VERSION_ID/
  rm -f $LOG_DIR/$PROJ_VERSION_ID/*
  echo "### Backing up logs..."
  find . -name *.elf | xargs -I% cp -f % $LOG_DIR/$PROJ_VERSION_ID/

fi

if [ -n "$UPLOAD_FS" ]
then
  echo "### Will upload tuning to file-system..."
  PROFILE_BASE="${PROFILE%.*}"
  TUNING_PATH="$PROFILE_BASE-tuning"
  rm -fr data
  ln -s `readlink -e $TUNING_PATH` data
  echo "### Uploading $TUNING_PATH"
  platformio run --target buildfs
  platformio run --target uploadfs
fi


if [ -n "$MONITOR" ]
then
  echo "### Monitoring..."
  { ./serial_monitor 0 > >(tee $LOG_DIR/$PROJ_VERSION_ID/stdout.txt ); } 2> >(tee $LOG_DIR/$PROJ_VERSION_ID/stderr.txt )
fi

echo "Done."


