#!/usr/bin/env bash

set -e
set -x

PROFILE="$1"
COMMIT_ID=`git rev-parse --short HEAD`
LOG_DIR=images

if [ -z "$PROFILE" ]
then
  echo "Profile missing"
  exit 1
fi

echo "### Using profile $PROFILE..."
export PLATFORMIO_BUILD_FLAGS="-D PROJ_VERSION=$COMMIT_ID `cat $PROFILE`" 

echo "### Compiling..."
platformio run

echo "### Checking if no changes to be committed..."
git diff --exit-code

echo "### Uploading..."
platformio run --target upload

echo "### Backing up image..."
mkdir -p $LOG_DIR/$COMMIT_ID/
rm -f $LOG_DIR/$COMMIT_ID/*
find . -name *.elf | xargs -I% cp -f % $LOG_DIR/$COMMIT_ID/

echo "### Monitoring..."


{ ./serial_monitor 0 > >(tee $LOG_DIR/$COMMIT_ID/stdout.txt ); } 2> >(tee $LOG_DIR/$COMMIT_ID/stderr.txt )
