#!/usr/bin/env bash

set -e
set -x

PROFILE="$1"
COMMIT_ID=`git rev-parse --short HEAD`

echo "### Checking if no changes to be committed..."
git diff --exit-code

echo "### Using profile $PROFILE..."
export PLATFORMIO_BUILD_FLAGS="-D PROJ_VERSION=$COMMIT_ID `cat $PROFILE`" 

echo "### Uploading..."
platformio run --target upload

echo "### Backing up image..."
mkdir -p images/$COMMIT_ID/
find . -name *.elf | xargs -I% cp -f % images/$COMMIT_ID/

echo "### Monitoring..."
./serial_monitor 0
